#!/usr/bin/env bash

set -e

until ( [ -x "dev" ] && [ -f "dev" ] ) || [ $PWD = "/" ]
do
    cd ..
done

if [ -x "dev" ] && [ -f "dev" ]
then
    ./dev "$@"
else
    echo "There is no executable \"dev\" script to run."
fi
